version: "3.9"

# create a local db to which the backend can connect
# (dotnet run)
services:
  sg-mysql:
    restart: always
    image: mysql:8.0.26
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sg
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - v-sg-mysql:/var/lib/mysql

volumes:
  v-sg-mysql:
    